pipeline {
    agent {
        docker {
            image 'maven:3.9.0-eclipse-temurin-17-alpine'
        }
    }

    stages {
        stage('Build') {
            steps {
                sh 'mvn package test'
            }
        }
    }
}

